version: "3"

vars:
  APP: poptimizer
  PYTHON: 3.11
  TOOLS: go-task rye mongodb-community nats-server

tasks:
  default:
    desc: List available tasks
    cmds:
      - task -l

  setup:
    desc: Setup venv, install tools and dependencies
    cmds:
      - brew tap mongodb/brew
      - brew install {{.TOOLS}}
      - rye pin --relaxed {{.PYTHON}} 
      - rye sync --update-all --all-features --no-lock --force

  update:
    desc: Upgrade tools and dependencies
    cmds:
      - brew upgrade {{.TOOLS}}
      - rye pin --relaxed {{.PYTHON}}
      - rye sync --update-all --all-features

  lint:
    desc: Format and lint
    cmds:
      - rye run ruff format {{.APP}}
      # - rye run lint-imports
      - rye run mypy {{.APP}}
      - rye run ruff {{.APP}}

  test:
    desc: Lint and test
    deps: [lint]
    cmds:
      - rye run pytest {{.APP}} --cov={{.APP}}

  run:
    desc: Run POptimizer with .env file
    cmds:
      - rye run {{.APP}}

  nats:
    desc: Run NATS Server.
    cmds:
      - nats-server --addr localhost --jetstream --store_dir nats
