version: "3"

vars:
  APP: poptimizer
  FRONTEND: frontend
  TOOLS: go-task uv npm mongodb-community mongosh

tasks:
  default:
    desc: List available tasks
    cmds:
      - task -l

  install:
    desc: Setup venv, install tools and dependencies
    cmds:
      - brew tap mongodb/brew
      - brew install {{.TOOLS}}
      - uv sync --frozen
      - cd {{.FRONTEND}} && npm install && npm run build

  update:
    desc: Upgrade tools and dependencies
    cmds:
      - brew upgrade {{.TOOLS}}
      - uv sync --upgrade
      - cd {{.FRONTEND}} && npm update --save --save-dev

  format:
    desc: Format
    cmds:
      - uv run ruff format {{.APP}}
      - uv run ruff check {{.APP}} --unsafe-fixes --exit-zero
      - cd {{.FRONTEND}} && npm run format

  lint:
    desc: Lint
    cmds:
      - uv run lint-imports
      - uv run ruff check {{.APP}} --unsafe-fixes --exit-non-zero-on-fix
      - uv run pyright {{.APP}}
      - cd {{.FRONTEND}} && npm run lint && npm run check

  test:
    desc: Test
    cmds:
      - uv run pytest {{.APP}} --cov={{.APP}}

  build:
    desc: Build frontend
    cmds:
      - task: format
      - task: lint
      - task: test
      - cd {{.FRONTEND}} && npm run build

  dev:
    desc: Develope frontend
    cmds:
      - cd {{.FRONTEND}} && npm run dev -- --open

  run:
    desc: Run POptimizer with .env file
    cmds:
      - uv run {{.APP}}

  mongo:
    desc: Run MongoDB Server
    cmds:
      - mongod --dbpath db --replSet POptimizer --bind_ip localhost &
      - mongosh --eval "rs.initiate()"
