version: "3"

vars:
  APP: poptimizer
  TOOLS: go-task uv npm mongodb-community mongodb-compass

tasks:
  default:
    desc: List available tasks
    cmds:
      - task -l

  install:
    desc: Setup venv, install tools and dependencies
    cmds:
      - brew tap mongodb/brew
      - brew reinstall {{.TOOLS}}
      - uv sync --frozen

  mongo:
    desc: Run MongoDB server service
    cmds:
      - brew services start mongodb-community
      
  update_ver:
    desc: Update POptimizer version
    cmds:
      - brew upgrade {{.TOOLS}}
      - rm -rf backup
      - mkdir backup
      - cp -r $(ls -A | grep -vF -e .venv -e .git) backup
      - git reset --hard
      - git pull

  update_div:
    desc: Update dividends from backup
    cmds:
      - uv run {{.APP}} div

  revert_ver:
    desc: Revert POptimizer to version form backup
    cmds:
      - rm -rf $(ls -A | grep -vF -e backup -e .venv -e .git)
      - cp -r backup/. . 

  run:
    desc: Run POptimizer
    cmds:
      - uv run {{.APP}} run

  format:
    desc: Format
    cmds:
      - uv run ruff format {{.APP}}
      - uv run ruff check {{.APP}} --unsafe-fixes --exit-zero

  lint:
    desc: Lint
    cmds:
      - uv run ruff format {{.APP}} --check
      - uv run ruff check {{.APP}} --unsafe-fixes --exit-non-zero-on-fix
      - uv run pyright {{.APP}}

  test:
    desc: Test
    cmds:
      - uv run pytest {{.APP}} --cov={{.APP}}

  update:
    desc: Update tools and dependencies
    cmds:
      - brew upgrade {{.TOOLS}}
      - uv sync --upgrade
