version: "3"

vars:
  APP: poptimizer
  FRONTEND: frontend
  PYTHON: 3.12
  TOOLS: go-task rye npm mongodb-community mongosh

tasks:
  default:
    desc: List available tasks
    cmds:
      - task -l

  install:
    desc: Setup venv, install tools and dependencies
    cmds:
      - brew tap mongodb/brew
      - brew install {{.TOOLS}}
      - rye pin --relaxed {{.PYTHON}}
      - rye sync --update-all --all-features --no-lock --force
      - cd {{.FRONTEND}} && npm install && npm run build

  update:
    desc: Upgrade tools and dependencies
    cmds:
      - brew upgrade {{.TOOLS}}
      - rye pin --relaxed {{.PYTHON}}
      - rye sync --update-all --all-features
      - cd {{.FRONTEND}} && npm update --save --save-dev

  format:
    desc: Format
    cmds:
      - rye run ruff format {{.APP}}
      - rye run ruff check {{.APP}} --unsafe-fixes --exit-zero
      - cd {{.FRONTEND}} && npm run format

  lint:
    desc: Lint
    cmds:
      - rye run lint-imports
      - rye run ruff check {{.APP}} --unsafe-fixes --exit-non-zero-on-fix
      - rye run pyright {{.APP}}
      - cd {{.FRONTEND}} && npm run lint && npm run check

  test:
    desc: Test
    cmds:
      - rye run pytest {{.APP}} --cov={{.APP}}

  build:
    desc: Build frontend
    cmds:
      - task: format
      - task: lint
      - task: test
      - cd {{.FRONTEND}} && npm run build

  dev:
    desc: Develope frontend
    cmds:
      - cd {{.FRONTEND}} && npm run dev -- --open

  run:
    desc: Run POptimizer with .env file
    cmds:
      - rye run {{.APP}}

  mongo:
    desc: Run MongoDB Server
    cmds:
      - mongod --dbpath db --replSet POptimizer --bind_ip localhost &
      - mongosh --eval "rs.initiate()"
