version: "3"

vars:
  APP: poptimizer
  PYTHON: 3.11
  TOOLS: go-task pdm mongodb-community nats-server

tasks:
  default:
    desc: List available tasks.
    cmds:
      - task -l

  setup:
    desc: Setup venv, install tools and dependencies.
    cmds:
      - brew install python@{{.PYTHON}}
      - brew tap mongodb/brew
      - brew install {{.TOOLS}}
      - pdm venv create --force {{.PYTHON}} 
      - task: update

  update:
    desc: Upgrade tools and dependencies.
    cmds:
      - brew upgrade {{.TOOLS}} python@{{.PYTHON}}
      - pdm update --update-all --no-sync
      - pdm sync --clean
      - pdm update --dry-run --unconstrained

  lint:
    desc: Format black and lint.
    cmds:
      - pdm run ruff format {{.APP}}
      # - pdm run lint-imports
      - pdm run mypy {{.APP}}
      - pdm run ruff {{.APP}}

  test:
    desc: Lint and test.
    deps: [lint]
    cmds:
      - pdm run pytest {{.APP}} --cov={{.APP}}

  run:
    desc: Run POptimizer with .env file.
    cmds:
    # Запуск не с помощью pdm, потому что не правильно обрабатываются сигналы SIGINT
      - .venv/bin/python -m {{.APP}}

  nats:
    desc: Run NATS Server.
    cmds:
      - nats-server --addr localhost --jetstream --store_dir nats
