"""Наименование столбцов."""
from typing import Final

DATE: Final = "DATE"
TICKER: Final = "TICKER"
DIVIDENDS: Final = "DIVIDENDS"
CPI: Final = "CPI"
ISIN: Final = "ISIN"
MARKET: Final = "MARKET"
LOT_SIZE: Final = "LOT_SIZE"
OPEN: Final = "OPEN"
CLOSE: Final = "CLOSE"
HIGH: Final = "HIGH"
LOW: Final = "LOW"
TURNOVER: Final = "TURNOVER"
