from collections.abc import AsyncIterator
from typing import Any, Protocol

from pydantic import BaseModel

from poptimizer.core import domain
from poptimizer.evolve.evolution import evolve


class Event(BaseModel):
    def __str__(self) -> str:
        return self.__repr__()


class AppStopped(Event): ...


class AppStarted(Event): ...


class Ctx(Protocol):
    def info(self, msg: str, *args: Any) -> None: ...
    def warning(self, msg: str, *args: Any) -> None: ...
    async def get[E: domain.Entity](
        self,
        t_entity: type[E],
        uid: domain.UID | None = None,
    ) -> E: ...
    async def get_for_update[E: domain.Entity](self, t_entity: type[E], uid: domain.UID | None = None) -> E: ...
    async def count_models(self) -> int: ...
    async def next_model_for_update(self) -> evolve.Model: ...
    async def delete_worst_model(self) -> None: ...
    async def get_models(self, day: domain.Day) -> list[evolve.Model]: ...
    async def sample_models(self, n: int) -> list[evolve.Model]: ...
    async def delete(self, entity: domain.Entity) -> None: ...
    def get_all[E: domain.Entity](self, t_entity: type[E]) -> AsyncIterator[E]: ...
    async def drop(self, entity_type: type[domain.Entity]) -> None: ...
    def send(self, event: Event) -> None: ...
