RUR: 0
USD: 0
positions:
  ABIO: 0
  ABRD: 0
  AFKS: 0
  AFLT: 0
  AGRO: 0
  AKMB: 0
  AKME: 0
  AKRN: 0
  ALRS: 0
  APTK: 0
  AQUA: 0
  BANE: 0
  BANEP: 0
  BELU: 0
  BLNG: 0
  BSPB: 0
  CBOM: 0
  CHMF: 0
  CHMK: 0
  CNTL: 0
  CNTLP: 0
  DVEC: 0
  ELFV: 0
  ENPG: 0
  EQMX: 0
  ETLN: 0
  FEES: 0
  FESH: 0
  FIVE: 0
  FIXP: 0
  FLOT: 0
  GAZP: 0
  GCHE: 0
  GMKN: 0
  GOLD: 0
  GTRK: 0
  HHRU: 0
  HYDR: 0
  INGR: 0
  IRAO: 0
  IRKT: 0
  KAZT: 0
  KLSB: 0
  KMAZ: 0
  KRKNP: 0
  KZOS: 0
  KZOSP: 0
  LIFE: 0
  LKOH: 0
  LNZL: 0
  LNZLP: 0
  LQDT: 0
  LSNG: 0
  LSNGP: 0
  LSRG: 0
  MAGN: 0
  MGNT: 0
  MGTSP: 0
  MOEX: 0
  MRKC: 0
  MRKP: 0
  MRKS: 0
  MRKU: 0
  MRKV: 0
  MRKZ: 0
  MSNG: 0
  MSRS: 0
  MTLR: 0
  MTLRP: 0
  MTSS: 0
  MVID: 0
  NKHP: 0
  NKNC: 0
  NKNCP: 0
  NLMK: 0
  NMTP: 0
  NVTK: 0
  OBLG: 0
  OGKB: 0
  OZON: 0
  PHOR: 0
  PIKK: 0
  PLZL: 0
  PMSB: 0
  PMSBP: 0
  POSI: 0
  PRFN: 0
  QIWI: 0
  RASP: 0
  RCMX: 0
  RGSS: 0
  RNFT: 0
  ROLO: 0
  ROSN: 0
  RTKM: 0
  RTKMP: 0
  RUAL: 0
  SBER: 0
  SBERP: 0
  SBGB: 0
  SBMM: 0
  SBMX: 0
  SBRB: 0
  SELG: 0
  SFIN: 0
  SGZH: 0
  SIBN: 0
  SMLT: 0
  SNGS: 0
  SNGSP: 0
  SPBE: 0
  SVAV: 0
  TATN: 0
  TATNP: 0
  TBRU: 0
  TCSG: 0
  TGKA: 0
  TGKB: 0
  TGKN: 0
  TMOS: 0
  TRMK: 0
  TRUR: 0
  TTLK: 0
  UNAC: 0
  UNKL: 0
  UPRO: 0
  VKCO: 0
  VSMO: 0
  VTBR: 0
  YAKG: 0
  YNDX: 0
  ZILL: 0
