RUR: 0
USD: 0
positions:
  AAL-RM: 0
  AAPL-RM: 0
  ABBV-RM: 0
  ABRD: 0
  ABT-RM: 0
  ADBE-RM: 0
  AFKS: 0
  AFLT: 0
  AGRO: 0
  AKMB: 0
  AKRN: 0
  ALRS: 0
  AMD-RM: 0
  AMEZ: 0
  AMZN-RM: 0
  APTK: 0
  AQUA: 0
  ATVI-RM: 0
  AVGO-RM: 0
  BA-RM: 0
  BABA-RM: 0
  BANE: 0
  BANEP: 0
  BELU: 0
  BIDU-RM: 0
  BIIB-RM: 0
  BLNG: 0
  BMY-RM: 0
  BRZL: 0
  BSPB: 0
  CAT-RM: 0
  CBOM: 0
  CHMF: 0
  CHMK: 0
  CMCSA-RM: 0
  CNTL: 0
  CNTLP: 0
  CRM-RM: 0
  COST-RM: 0
  CSCO-RM: 0
  CVX-RM: 0
  DIOD: 0
  DIS-RM: 0
  DSKY: 0
  EA-RM: 0
  EBAY-RM: 0
  ENPG: 0
  ENRU: 0
  ETLN: 0
  F-RM: 0
  FB-RM: 0
  FDX-RM: 0
  FEES: 0
  FESH: 0
  FIVE: 0
  FIXP: 0
  FLOT: 0
  FXCN: 0
  FXGD: 0
  FXIT: 0
  FXKZ: 0
  FXMM: 0
  FXRB: 0
  FXRU: 0
  GAZP: 0
  GCHE: 0
  GE-RM: 0
  GEMA: 0
  GILD-RM: 0
  GLTR: 0
  GM-RM: 0
  GMKN: 0
  GOOG-RM: 0
  GPS-RM: 0
  GTRK: 0
  HHRU: 0
  HIMCP: 0
  HPQ-RM: 0
  HYDR: 0
  IBM-RM: 0
  INGR: 0
  INTC-RM: 0
  IRAO: 0
  IRKT: 0
  ISKJ: 0
  JNJ-RM: 0
  KAZT: 0
  KHC-RM: 0
  KLSB: 0
  KMAZ: 0
  KO-RM: 0
  KRKNP: 0
  KZOS: 0
  LIFE: 0
  LKOH: 0
  LNTA: 0
  LNZL: 0
  LNZLP: 0
  LSNG: 0
  LSNGP: 0
  LSRG: 0
  MA-RM: 0
  MAGN: 0
  MCD-RM: 0
  MDMG: 0
  MGNT: 0
  MGTSP: 0
  MOEX: 0
  MRKC: 0
  MRKP: 0
  MRKS: 0
  MRKU: 0
  MRKV: 0
  MRKY: 0
  MRKZ: 0
  MRNA-RM: 0
  MSFT-RM: 0
  MSNG: 0
  MSRS: 0
  MSTT: 0
  MTLR: 0
  MTLRP: 0
  MTSS: 0
  MU-RM: 0
  MVID: 0
  NEE-RM: 0
  NEM-RM: 0
  NFAZ: 0
  NFLX-RM: 0
  NKE-RM: 0
  NKHP: 0
  NKNC: 0
  NKNCP: 0
  NLMK: 0
  NMTP: 0
  NSVZ: 0
  NVDA-RM: 0
  NVTK: 0
  OGKB: 0
  ORCL-RM: 0
  ORUP: 0
  OZON: 0
  PFE-RM: 0
  PG-RM: 0
  PHOR: 0
  PIKK: 0
  PLZL: 0
  PMSBP: 0
  POGR: 0
  POLY: 0
  PTR-RM: 0
  PYPL-RM: 0
  QCOM-RM: 0
  QIWI: 0
  RASP: 0
  RBCM: 0
  REGN-RM: 0
  RGSS: 0
  RNFT: 0
  ROLO: 0
  ROSN: 0
  RSTI: 0
  RSTIP: 0
  RTKM: 0
  RTKMP: 0
  RUAL: 0
  RUGR: 0
  RUSE: 0
  RZSB: 0
  SBER: 0
  SBERP: 0
  SBGB: 0
  SBRB: 0
  SELG: 0
  SFIN: 0
  SIBN: 0
  SMLT: 0
  SNGS: 0
  SNGSP: 0
  SBUX-RM: 0
  SUGB: 0
  SVAV: 0
  T-RM: 0
  TATN: 0
  TATNP: 0
  TCSG: 0
  TGKA: 0
  TGKB: 0
  TGKD: 0
  TGKN: 0
  TGT-RM: 0
  TMUS-RM: 0
  TRMK: 0
  TRNFP: 0
  TRUR: 0
  TSLA-RM: 0
  TTLK: 0
  TTWO-RM: 0
  TWTR-RM: 0
  UBER-RM: 0
  UNAC: 0
  UNH-RM: 0
  UNKL: 0
  UPRO: 0
  USBN: 0
  V-RM: 0
  VKCO: 0
  VRSB: 0
  VSMO: 0
  VTBB: 0
  VTBM: 0
  VTBR: 0
  VTRS-RM: 0
  WMT-RM: 0
  XOM-RM: 0
  YAKG: 0
  YNDX: 0
  ZILL: 0
